
tcp:
	gcc -o visualizer_tcp visualizer_tcp.c -fanalyzer -lSOIL -lglew32 -lopengl32 -lglu32 -lglfw3 -lws2_32 -Wl,--stack,10485760
udp:
	gcc -o visualizer_udp visualizer_udp.c -fanalyzer -lSOIL -lglew32 -lopengl32 -lglu32 -lglfw3 -lws2_32 -Wl,--stack,20485760
	
